# ----------------- Logistic Regression Using Sklearn -------------------

### Importing Libraries

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv("https://raw.githubusercontent.com/sahdevsaini/Data-Set/main/Written_Tests.csv")

In [28]:
df.head()

Test 1     Test 2  Results
0  34.623660  78.024693        0
1  30.286711  43.894998        0
2  35.847409  72.902198        0
3  60.182599  86.308552        1
4  79.032736  75.344376        1

### Dividing feature into independent and dependent feature 

In [9]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [10]:
X

Test 1     Test 2
0   34.623660  78.024693
1   30.286711  43.894998
2   35.847409  72.902198
3   60.182599  86.308552
4   79.032736  75.344376
..        ...        ...
95  83.489163  48.380286
96  42.261701  87.103851
97  99.315009  68.775409
98  55.340018  64.931938
99  74.775893  89.529813

[100 rows x 2 columns]

In [12]:
y

0     0
1     0
2     0
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    1
Name: Results, Length: 100, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=.20,random_state=42)

In [14]:
X_train

Test 1     Test 2
55  49.586677  59.808951
88  78.635424  96.647427
26  80.190181  44.821629
42  94.443368  65.568922
69  66.746719  60.991394
..        ...        ...
60  75.395611  85.759937
71  64.039320  78.031688
14  39.538339  76.036811
92  55.482161  35.570703
51  99.272527  60.999031

[80 rows x 2 columns]

In [32]:
from sklearn.linear_model import LogisticRegression
regression = LogisticRegression()

In [33]:
regression

LogisticRegression()

In [34]:
#import warnings
#from sklearn.exceptions import ConvergenceWarning
#from sklearn.model_selection import GridSearchCV     # Import GridSearchCV for hyperparameter tuning
#warnings.filterwarnings("ignore", category=ConvergenceWarning)
#parameter = {'C': [1,2,3,4,10,20,30,50],'penalty' : ['l1','l2','elasticnet']}

#log_regressor = GridSearchCV(regression,parameter,scoring = 'accuracy',cv = 5)
#log_regressor.fit(X,y)

In [47]:
logistic_regessor = regression.fit(X,y)

In [51]:
coefficients = logistic_regessor.coef_
coefficients

array([[0.20535491, 0.2005838 ]])

In [52]:
intercept = logistic_regessor.intercept_
intercept

array([-25.05219314])

In [ ]:
logistic_regessor.coff

In [35]:
log_regressor.best_params_

{'C': 2, 'penalty': 'l2'}

In [36]:
log_regressor.best_score_


0.9

In [39]:
Prediction_log = logistic_regessor.predict(X_test)

In [40]:
Prediction_log

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [41]:
df.corr()

Test 1    Test 2   Results
Test 1   1.000000 -0.023665  0.574057
Test 2  -0.023665  1.000000  0.512323
Results  0.574057  0.512323  1.000000

In [42]:
#sns.pairplot(df,hue = 'species')

In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_recall_curve,roc_auc_score,f1_score

In [44]:
confusion_matrix(y_test,Prediction_log)

array([[ 7,  1],
       [ 2, 10]])

In [45]:
f1_score(y_test, Prediction_log, average='micro')

0.85